<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class BooksTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $bookManagers = [1, 2, 3]; // 3人のマネージャーの識別子

        DB::table('books')->insert([
            [
                'title' => '巨匠とマルガリータ',
                'author' => 'ミハイル・ブルガーコフ',
                'publication_date' => '1967',
                'genre' => '小説',
                'description' => '「マスターとマルガリータ」は、複数のプロットラインが交差する力強い小説です。主要なプロットは、悪魔がソビエトのモスクワを訪れ、その存在が様々なキャラクターの人生に与える影響を描いています。その中には、作家であるマスターと彼の愛人であるマルガリータも含まれています。この小説は哲学、風刺、ファンタジー、そしてマジックリアリズムが混ざり合ったものであり、読者には信仰、善悪、創造性の本質、そして人間の情熱について深く考えさせる要素が含まれています。',
                'cover_image' => 'cover_images/book1_Master.jpg',
                'book_manager_id' => $bookManagers[array_rand($bookManagers)], // ランダム・マネージャー
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'エヴゲーニイ・オネーギン',
                'author' => 'アレクサンドル・プーシキン',
                'publication_date' => '1825',
                'genre' => '韻文小説',
                'description' => '「エヴゲーニイ・オネーギン」はロシアの詩人アレクサンドル・プーシキンによる詩的な長編小説です。物語は主人公エフゲニー・オネーギンとその友人たち、特にタチアナとの複雑な愛の物語を描いています。作品はロマン派の影響を受けつつも、リアリズムの特徴も持っており、ロシアの社会や人間の心理を深く掘り下げています。愛、友情、孤独、社会的責任など、様々なテーマが織り交ぜられており、読者に感情的な共感と深い考察を促します。',
                'cover_image' => 'cover_images/book2_Onegin.jpg',
                'book_manager_id' => $bookManagers[array_rand($bookManagers)],
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => '罪と罰',
                'author' => 'フョードル・ドストエフスキー',
                'publication_date' => '1866',
                'genre' => '小説',
                'description' => '「罪と罰」はロシアの作家フョードル・ドストエフスキーによる傑作小説です。物語は主人公ラスコルニコフと彼の心理的な葛藤、犯罪行為とその後の贖罪のプロセスを描いています。ドストエフスキーの作品はリアリズムの枠組み内で人間の内面や道徳的な問題を深く探求し、精神的な葛藤や罪悪感、愛と贖罪のテーマを掘り下げています。読者は登場人物たちの複雑な感情や行動を通じて、人間の本質について深い洞察を得ることができます。',
                'cover_image' => 'cover_images/book3_Prestuplenie.jpg',
                'book_manager_id' => $bookManagers[array_rand($bookManagers)],
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => '戦争と平和',
                'author' => 'レフ・トルストイ',
                'publication_date' => '1869',
                'genre' => '長編小説',
                'description' => '「戦争と平和」はロシアの作家レフ・トルストイによる傑作長編小説です。物語はナポレオン戦争を背景に、主要登場人物たちの愛、友情、戦争の中での生き残りを描いています。トルストイの筆致はリアリズムの精神を受け継ぎつつも、人間の内面や運命、歴史の流れを深く追求しています。登場人物たちは戦争や政治の影響を受けながらも、自己成長や愛情を見出し、読者に生きる意味や人間の真実について考えさせます。作品は壮大なスケールでロシア社会や人間の複雑な関係を描き、文学的な傑作として高く評価されています。',
                'cover_image' => 'cover_images/book4_War.jpg',
                'book_manager_id' => $bookManagers[array_rand($bookManagers)],
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => '星の王子さま',
                'author' => 'アントワーヌ・ド・サン＝テグジュペリ',
                'publication_date' => '1943',
                'genre' => '寓話',
                'description' => '「星の王子さま」はアントワーヌ・ド・サン＝テグジュペリによる寓話的な物語です。主人公である小さな王子がさまざまな惑星を訪れ、そこで出会う様々な人々との交流を通じて、生きる意味や友情、愛情、責任についての哲学的な考察が織り込まれています。物語は子供から大人まで幅広い読者に愛され、シンプルでありながら深いメッセージを伝えるテクストとして高く評価されています。また、挿絵も含まれており、物語にさらなる魅力を与えています。',
                'cover_image' => 'cover_images/book5_LittlePrince.jpg',
                'book_manager_id' => $bookManagers[array_rand($bookManagers)],
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => '現代の英雄',
                'author' => 'ミハイル レールモントフ',
                'publication_date' => '1840',
                'genre' => '小説',
                'description' => '「我々の時代の英雄」はミハイル・リョーダンツェフによるロシアの小説で、ロマンティック・リアリズムの影響を受けています。物語は主人公ペチョーリンの複雑な内面と現実世界での苦悩を描いています。ペチョーリンは時代を象徴するようなキャラクターであり、彼の行動や精神状態はロシアの社会や文化を反映しています。この小説は人間の欲望、愛、孤独、そして時代の矛盾について深く探求し、読者に強い共感と考えさせる要素を提供します。',
                'cover_image' => 'cover_images/book6_Hero.jpg',
                'book_manager_id' => $bookManagers[array_rand($bookManagers)],
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => '十二の椅子',
                'author' => 'イリヤ・イリフとエフゲニー・ペトロフ',
                'publication_date' => '1928',
                'genre' => 'アドベンチャー',
                'description' => '「十二の椅子」はイリヤ・イルフとエフゲニー・ペトロフによるロシアのユーモア小説です。物語は、ボリシェヴィキ革命後のソ連を舞台に、12脚の貴重な椅子の捜索を巡る冒険を描いています。主人公のオスィーニンとクラウゼが、椅子の内部に隠された貴重な宝物を求めてさまざまな場所を訪れる過程で、笑いと興奮に満ちた出来事が展開します。この小説は、ロシアの社会や政治に対する風刺や批評も含んでおり、読者に楽しみながらも考えさせる要素を提供します。',
                'cover_image' => 'cover_images/book7_Chairs.jpg',
                'book_manager_id' => $bookManagers[array_rand($bookManagers)],
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => '1984年',
                'author' => 'ジョージ・オーウェル',
                'publication_date' => '1949',
                'genre' => 'ダイストピアン小説',
                'description' => '「1984年」はジョージ・オーウェルによるダイストピアン小説で、現実世界とは異なる未来の社会を描いています。物語はスパイとして働くウィンストン・スミスが、全体主義的な政府による監視と統制の中で生きる姿を中心に展開します。政府の監視や言論統制、個人の自由への侵害など、さまざまなテーマが取り上げられており、読者に社会や政治に対する深い洞察を与えます。この小説は非常に影響力があり、現代の政治や社会にも多大な影響を与えています。',
                'cover_image' => 'cover_images/book8_1984.jpg',
                'book_manager_id' => $bookManagers[array_rand($bookManagers)],
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => '百年の孤独',
                'author' => 'ガブリエル・ガルシア・マルケス',
                'publication_date' => '1967',
                'genre' => '魔法リアリズム',
                'description' => '「百年の孤独」はガブリエル・ガルシア・マルケスによるラテンアメリカ文学の代表作であり、魔法リアリズムの傑作として知られています。物語はブエンディア家の7代にわたる物語を通じて、マコンドという架空の町の歴史と住民たちの運命を描いています。魔法や奇跡が日常に溶け込む中で、愛、孤独、死、家族、運命などさまざまなテーマが織り込まれています。この小説は言葉の魔術を駆使して読者を魅了し、ラテンアメリカ文学の傑作として高く評価されています。',
                'cover_image' => 'cover_images/book9_Hundread.jpg',
                'book_manager_id' => $bookManagers[array_rand($bookManagers)],
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'ハリー・ポッターと賢者の石',
                'author' => 'J.K.ローリング',
                'publication_date' => '1997',
                'genre' => 'ファンタジー',
                'description' => '「ハリー・ポッターと賢者の石」はJ.K.ローリングによるファンタジー小説の最初の作品です。物語は魔法界とノーマル界の間で生きる少年ハリー・ポッターの冒険を中心に展開します。彼が魔法学校ホグワーツに入学し、友達と共に魔法の謎や冒険に挑む姿が描かれます。賢者の石をめぐる物語は魔法の要素を取り入れつつも、友情や勇気、成長と自己発見に関するテーマも深く掘り下げられています。この作品は多くの読者に愛され、世界中で人気を博しています。',
                'cover_image' => 'cover_images/book10_HarryPotter.jpg',
                'book_manager_id' => $bookManagers[array_rand($bookManagers)],
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => '死せる魂',
                'author' => 'ニコライ・ゴーゴリ',
                'publication_date' => '1842',
                'genre' => 'サティア',
                'description' => '「死せる魂」はニコライ・ゴーゴリによるロシア文学の名作です。物語は主人公チチコフがロシアの田舎町を訪れ、死んだ農奴の名前を使って彼らの「死せる魂」を購入しようとする姿を描いています。この小説はロシアの社会や貴族階級、農奴制度を風刺的に描写し、人間の欲望や欠点、道徳的な葛藤を探求します。ゴーゴリの独特な筆致と風刺的な要素が組み合わさり、この作品はロシア文学の中でも特に重要な位置を占めています。',
                'cover_image' => 'cover_images/book11_DeathSoul.jpg',
                'book_manager_id' => $bookManagers[array_rand($bookManagers)],
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'アンナ・カレーニナ',
                'author' => 'レフ・トルストイ',
                'publication_date' => '1877',
                'genre' => '小説',
                'description' => '「アンナ・カレーニナ」はレフ・トルストイによるロシア文学の古典的な作品です。物語は主人公アンナ・カレーニナと彼女の不倫相手であるヴロンスキー伯爵の恋愛と苦悩を中心に展開します。一方で、アンナの夫であるカレーニン伯爵や他の登場人物たちの物語も平行して進行し、ロシアの上流社会の風俗や道徳、人間の欲望と苦悩、家族や愛情の複雑な関係を描写しています。トルストイのリアリズムと精緻なキャラクター描写が光るこの作品は、ロシア文学の巨匠の一つとして高く評価されています。',
                'cover_image' => 'cover_images/book12_AnnaK.jpg',
                'book_manager_id' => $bookManagers[array_rand($bookManagers)],
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => '白痴',
                'author' => 'フョードル・ドストエフスキー',
                'publication_date' => '1869',
                'genre' => '小説',
                'description' => '「白痴」はフョードル・ドストエフスキーによるロシア文学の名作です。物語は主人公であるムィシキン公子の生涯を中心に展開します。ムィシキン公子は心優しいが社会的には不器用であり、彼の純粋さや善意が時に周囲の人々を翻弄する様子が描かれます。物語はロシアの上流社会や貴族たちの複雑な人間関係、宗教や道徳、愛情と憎しみなどを深く掘り下げ、人間の心理や社会の闇を描写しています。この小説はドストエフスキーの魂の深さとキャラクター描写の優れた点が特徴であり、ロシア文学の中でも重要な作品の一つです。',
                'cover_image' => 'cover_images/book13_Idiot.jpg',
                'book_manager_id' => $bookManagers[array_rand($bookManagers)],
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'ドリアン・グレイの肖像',
                'author' => 'オスカー・ワイルド',
                'publication_date' => '1890',
                'genre' => '小説',
                'description' => '「ドリアン・グレイの肖像」はオスカー・ワイルドによるゴシック小説の名作です。物語は美しい若者ドリアン・グレイが自分の肖像画を通じて歳を取らず美しさを保つことを願うという題材を中心に展開します。彼の美しさと無垢さが絵画に宿ることで、肖像画は彼の代わりに老化していくという不思議な現象が起こります。一方で、ドリアンの心は堕落し、悪徳の生活を送るようになっていきます。この小説は美と悪徳、罪と贖罪、現実と理想の対比などをテーマに、人間の欲望とその代償を描写しています。',
                'cover_image' => 'cover_images/book14_DorianGray.jpg',
                'book_manager_id' => $bookManagers[array_rand($bookManagers)],
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => '知恵の悲しみ',
                'author' => 'アレクサンドル・グリボエードフ',
                'publication_date' => '1825',
                'genre' => '喜劇',
                'description' => '「知恵の悲しみ」はロシア文学の戯曲であり、アレクサンドル・グリボエードフによって書かれました。物語は主人公のチャツキーが上流社会の偽善と虚栄心に悩む姿を中心に展開します。彼の知識と才能が時に周囲との軋轢を生み、さまざまなコミカルな状況が生まれます。この作品はロシア社会の風刺や風俗を描写し、知識人の孤独や社会の偽善について深く考察しています。また、言葉遊びや機知に富んだ対話が特徴であり、ロシア文学の名作の一つとして高く評価されています。',
                'cover_image' => 'cover_images/book15_Griboedov.png',
                'book_manager_id' => $bookManagers[array_rand($bookManagers)],
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => '父と子',
                'author' => 'ツルゲーネフ',
                'publication_date' => '1862',
                'genre' => '小説',
                'description' => '「父と子」はイワン・タージェフニコフによるロシア文学の名作です。物語は主人公のヴラージミル・バーザロフと彼の父親であるニーヒル・バーザロフとの対立や葛藤を描いています。ヴラージミルは新しいアイデアや自由な思想を追求する若者であり、父親の保守的な価値観と衝突します。物語は彼らの対立を通じて、19世紀のロシア社会や世代間の摩擦、愛と理解の重要性などを探求します。また、登場人物たちの心理描写やリアリズムの手法が特徴であり、タージェフニコフの代表作として高く評価されています。',
                'cover_image' => 'cover_images/book16_FatherChild.jpg',
                'book_manager_id' => $bookManagers[array_rand($bookManagers)],
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => '指輪物語',
                'author' => 'J.R.R.トールキン',
                'publication_date' => '1954',
                'genre' => 'ファンタジー',
                'description' => '「指輪物語」はJ.R.R.トールキンによるファンタジー文学の巨編です。物語はミドルアースと呼ばれる架空の世界を舞台に、力を持つ一つの指輪をめぐる冒険を描いています。指輪は強大な力を持ち、それを手に入れた者は世界を支配することができるとされています。しかし、指輪には闇の王サウロンの邪悪な影響があり、指輪を破壊しなければなりません。物語はフロド・バギンズやその仲間たちが指輪を破壊するための旅を描き、友情や勇気、希望と絶望をテーマにしています。トールキンの豊かな想像力と言語の創造力が光るこの作品は、ファンタジー文学の古典的な傑作として世界中で愛されています。',
                'cover_image' => 'cover_images/book17_LordOfRings.jpg',
                'book_manager_id' => $bookManagers[array_rand($bookManagers)],
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => '麦畑でつかまえて',
                'author' => 'J.D.サリンジャー',
                'publication_date' => '1951',
                'genre' => '小説',
                'description' => '「麦畑でつかまえて」はJ.D.サリンジャーによるアメリカの現代文学の名作です。物語は主人公ホールデン・コールフィールドの視点から語られ、彼の心の葛藤や成長を描いています。ホールデンは社会や現実に適応できず、世間に対する不満や孤独感を抱えています。物語は彼がニューヨークをさまよい歩きながら、自分や周囲の人々との関係、成長と青春の問題に直面する姿を描写します。この作品は青春期の葛藤や心の成長をリアルに描いたことから、多くの読者に愛されています。',
                'cover_image' => 'cover_images/book18_NadPropasti.jpg',
                'book_manager_id' => $bookManagers[array_rand($bookManagers)],
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => '三人の仲間',
                'author' => 'エーリヒ・マリア・レマルク',
                'publication_date' => '1937',
                'genre' => 'ドラマ',
                'description' => '「三人の仲間」はエーリヒ・マリア・レマルクによるドイツの小説です。物語は第一次世界大戦後のドイツを舞台に、主人公のロベルトと彼の親友であるハンスとアルバートの三人の友情と生き方を描いています。彼らは戦場で出会い、戦争の傷跡を抱えながらも、新たな人生を築いていこうとする姿が描かれます。特にロベルトとアルバートの愛と友情、そして恋愛や人間関係の複雑さが物語の中心になっています。この小説は戦争と平和、友情と愛情、人間の強さと脆さを深く掘り下げた作品として知られています。',
                'cover_image' => 'cover_images/book19_TreeComrad.jpg',
                'book_manager_id' => $bookManagers[array_rand($bookManagers)],
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'ドクトル・ジヴァゴ',
                'author' => 'ボリス・パステルナーク',
                'publication_date' => '1957',
                'genre' => '歴史小説',
                'description' => '「ドクトル・ジヴァゴ」はボリス・パステルナークによるロシア文学の名作です。物語は主人公のユーリイ・ジバゴが第一次世界大戦とロシア革命の間に生きる姿を描いています。彼は詩人であり医者でもあり、複雑な愛情や政治的な運命に巻き込まれながら生きていきます。特に彼と愛する女性リアが描かれる恋愛や苦悩、そしてロシアの歴史的な転換期における人間の運命と道徳的な葛藤が物語の中心となっています。この小説はロシアの風景や人間の心理、愛と革命、そして芸術と政治の対立をテーマに、壮大な叙事詩として高く評価されています。',
                'cover_image' => 'cover_images/book20_DoctorG.jpg',
                'book_manager_id' => $bookManagers[array_rand($bookManagers)],
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => '人間失格',
                'author' => '太宰治',
                'publication_date' => '1948',
                'genre' => '小説',
                'description' => '太宰治による「人間失格」は、現代日本文学の重要な作品の一つです。物語は主人公である斎藤茂吉の内面の葛藤と自己破壊的な生き方を描いています。茂吉は自己嫌悪や孤独感に苦しみながらも、それを打破することができずに堕落し、破滅への道を歩んでいきます。この小説は茂吉の内面の葛藤や社会との摩擦を通じて、人間の複雑な心理や現代社会の問題を深く描写しています。また、太宰治の独特な文体や哲学的なテーマが際立っており、多くの読者に衝撃を与える作品として知られています。',
                'cover_image' => 'cover_images/book21_People.jpg',
                'book_manager_id' => $bookManagers[array_rand($bookManagers)],
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'こころ',
                'author' => '夏目 漱石',
                'publication_date' => '1914',
                'genre' => '小説',
                'description' => '夏目漱石による「こころ」は、日本近代文学の古典として非常に有名な作品です。物語は主人公の先生と、彼を取り巻く人々の心の葛藤や人間関係を描いています。先生は高潔で思慮深い人物でありながら、内面には複雑な感情や苦悩を抱えています。彼の人生や選択、そして周囲の人々との関わりが、作品全体を通じて丁寧に描かれています。また、作品中には多くの日本文化や哲学的なテーマも含まれており、日本文学の傑作として広く称賛されています。',
                'cover_image' => 'cover_images/book22_Money.jpg',
                'book_manager_id' => $bookManagers[array_rand($bookManagers)],
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => '破戒',
                'author' => '島崎 藤村',
                'publication_date' => '1906',
                'genre' => '小説',
                'description' => '「破戒」は島崎藤村による日本の近代文学の作品であり、彼の代表作の一つです。物語は主人公の亀井勝一郎と彼の妻である綾子の関係を中心に展開されます。勝一郎は大学教授でありながら、綾子との不倫関係に陥ってしまいます。この過ちが彼らの人生に大きな影響を与え、その結末に至るまでが描かれています。作品は当時の日本社会の風俗や倫理観、男女の関係の複雑さをリアルに描写し、島崎藤村の文学的才能と深い洞察力を示す作品として評価されています。',
                'cover_image' => 'cover_images/book23_Ocean.jpg',
                'book_manager_id' => $bookManagers[array_rand($bookManagers)],
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => '沈黙',
                'author' => '遠藤 周作',
                'publication_date' => '1966',
                'genre' => '小説',
                'description' => '遠藤周作による「沈黙」は、日本文学の名作として知られています。物語は17世紀のキリシタン弾圧時代の日本を舞台に、宣教師であるロドリゲス神父の苦悩と信仰の葛藤を描いています。神父は日本においてキリシタンを弾圧する当局に対し、信仰を守るか、あるいは弾圧を受け入れるかという選択を迫られます。物語は彼の内面の葛藤や日本社会の歴史的背景を背景に、宗教的な問いと人間の矛盾を探求します。作品は遠藤周作の深い哲学的洞察と文学的技量を示すとともに、宗教、信仰、文化の融合と対立について深く考えさせる作品として高い評価を得ています。',
                'cover_image' => 'cover_images/book24_Cloud.jpg',
                'book_manager_id' => $bookManagers[array_rand($bookManagers)],
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => '砂の女',
                'author' => '安部 公房',
                'publication_date' => '1962',
                'genre' => '長編小説',
                'description' => '安部公房の「砂の女」は、日本の現代文学の中でも特に注目される作品の一つです。物語は主人公の男性が砂漠地帯に住む不思議な女性との出会いを通じて、現実と夢の境界や愛と孤独、人間の存在意義を問う内容が描かれています。作品は非常に象徴的で実験的な文体を持ち、読者に多くの解釈の余地を残すことで知られています。また、安部公房の他の作品と同様に、心理的な描写や物語の構造が複雑であり、文学の可能性を広げる意欲的な作品として評価されています。',
                'cover_image' => 'cover_images/book25_Woman.jpg',
                'book_manager_id' => $bookManagers[array_rand($bookManagers)],
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => '仮面の告白',
                'author' => '三島 由紀夫',
                'publication_date' => '1949',
                'genre' => '長編小説',
                'description' => '三島由紀夫の「仮面の告白」は、日本の現代文学の中でも重要な作品の一つです。物語は主人公の青年が、自らの過去と現在の葛藤、そして心の内面を告白するという形式で進行します。青年は過去の出来事によって心に傷を負い、それを抱えながらも現実と向き合おうとする姿が描かれます。作品は三島由紀夫の繊細な文体と心理描写が特徴であり、人間の複雑な感情や過去との向き合い方を深く掘り下げた作品として評価されています。また、社会的なテーマや倫理観も含まれており、多くの読者に感銘を与える作品として知られています。',
                'cover_image' => 'cover_images/book26_Man.jpg',
                'book_manager_id' => $bookManagers[array_rand($bookManagers)],
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => '坊つちやん',
                'author' => '夏目 漱石',
                'publication_date' => '1906',
                'genre' => '長編小説',
                'description' => '夏目漱石の「坊っちゃん」は、日本の近代文学の古典的な作品の一つです。物語は主人公である宮沢賢治の生涯を中心に展開されます。賢治は、師範学校の教員として若い生徒たちとの交流を通じて成長し、自らの教育理念や生き方を模索していきます。作品は教育者としての賢治の姿や彼が直面する様々な問題、そして時代背景が描かれており、日本の教育や社会に対する批評が含まれています。また、夏目漱石の鋭い観察力と文学的な表現力が光る作品として、多くの読者に愛されています。',
                'cover_image' => 'cover_images/book27_Square.jpg',
                'book_manager_id' => $bookManagers[array_rand($bookManagers)],
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => '告白',
                'author' => '湊 かなえ',
                'publication_date' => '2008',
                'genre' => 'ミステリー',
                'description' => '湊かなえの「告白」は、日本のサスペンス小説の中でも注目される作品の一つです。物語は主人公の教師が、かつての生徒である女性からの手紙を受け取り、それをきっかけに事件の真相に迫っていく姿を描いています。作品は緊迫感あふれる展開と、登場人物たちの心理描写が特徴であり、読者を引き込むサスペンスとして高い評価を得ています。また、人間関係や過去の影響などもテーマとして掘り下げられており、複雑な心の機微を描いた作品としても知られています。',
                'cover_image' => 'cover_images/book28_School.jpg',
                'book_manager_id' => $bookManagers[array_rand($bookManagers)],
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'コンビニ人間',
                'author' => '村田 沙耶香',
                'publication_date' => '2016',
                'genre' => '文芸フィクション',
                'description' => '村田沙耶香の「コンビニ人間」は、現代日本の労働環境と社会の価値観を鋭く風刺した作品です。物語は、主人公の古倉恵子がコンビニエンスストアで働く日常を通じて、自身のアイデンティティや社会との関係を見つめ直す姿を描いています。恵子はコンビニでの規則正しい生活に安心を見出し、他人の期待や社会の規範に疑問を持ちながらも、次第に自身の存在意義を探求します。作品は、現代社会の異質性と適応についての深い洞察を提供し、多くの読者に共感と考察を促す文学作品として評価されています。',
                'cover_image' => 'cover_images/book29_Conbini.jpg',
                'book_manager_id' => $bookManagers[array_rand($bookManagers)],
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => '車輪の下',
                'author' => 'ヘルマン・ヘッセ',
                'publication_date' => '1906',
                'genre' => 'フィクション',
                'description' => 'ヘルマン・ヘッセの「車輪の下」は、若者の成長と社会の圧力をテーマにした小説です。物語は、才能ある少年ハンス・ギーベンラートが、厳しい教育制度と過剰な期待に押しつぶされながらも、自分自身を見つけるために苦闘する姿を描いています。ハンスは優れた学生でありながら、厳格な父親と教師の期待に応えようとする中で、精神的に追い詰められていきます。作品は、教育制度の問題点や社会の価値観、人間の内面的な葛藤を深く掘り下げて描写しており、多くの読者に強い共感と深い洞察を提供する作品として評価されています。',
                'cover_image' => 'cover_images/book30_German.jpg',
                'book_manager_id' => $bookManagers[array_rand($bookManagers)],
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'モンテ・クリスト伯',
                'author' => 'アレクサンドル・デュマ',
                'publication_date' => '1844',
                'genre' => 'フィクション',
                'description' => '「モンテ・クリスト伯」は、アレクサンドル・デュマによるフランスの冒険小説です。物語は、若き船乗りエドモン・ダンテスが、無実の罪で投獄されることから始まります。彼は牢獄で知り合った老囚人から莫大な財宝のありかを聞き出し、脱獄後にその財宝を手に入れ、「モンテ・クリスト伯」として新たな人生を歩み始めます。彼の目的は、自分を陥れた者たちに復讐を果たすことです。物語は、エドモンの復讐の過程と、彼が直面する人間関係や道徳的な葛藤を描いています。この作品は、緻密なプロット、豊かなキャラクター描写、そして復讐と赦しという普遍的なテーマが特徴であり、世界中で愛され続けています。',
                'cover_image' => 'cover_images/book31_Graf.jpg',
                'book_manager_id' => $bookManagers[array_rand($bookManagers)],
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => '不思議の国のアリス',
                'author' => 'ルイス・キャロル',
                'publication_date' => '1865',
                'genre' => 'ファンタジー',
                'description' => '「不思議の国のアリス」は、ルイス・キャロルによる児童文学の古典的作品です。物語は、主人公のアリスがうさぎの穴に落ち、奇妙で幻想的な世界に迷い込むところから始まります。彼女はその世界で、チェシャ猫、ハートの女王、帽子屋など、風変わりで魅力的なキャラクターたちに出会いながら、数々の不思議な冒険を繰り広げます。キャロルの独特な言葉遊びと論理的なパズル、そして幻想的なイメージが豊かに盛り込まれたこの作品は、子どもから大人まで幅広い読者に愛されています。物語の深層には、ヴィクトリア朝時代の社会風刺や哲学的テーマも含まれており、読むたびに新たな発見があるとされています。',
                'cover_image' => 'cover_images/book32_Alice.jpg',
                'book_manager_id' => $bookManagers[array_rand($bookManagers)],
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'シャーロック・ホームズ',
                'author' => 'アーサー・コナン・ドイル',
                'publication_date' => '1887',
                'genre' => 'ミステリー',
                'description' => 'アーサー・コナン・ドイルによる「シャーロック・ホームズ」シリーズは、世界中で最も有名な探偵小説の一つです。物語は、天才探偵シャーロック・ホームズと彼の信頼できる友人兼助手のジョン・ワトソン博士の視点から描かれています。ホームズは、優れた観察力と推理力を駆使して、数々の複雑な事件を解決していきます。シリーズは「緋色の研究」に始まり、「四つの署名」、「バスカヴィル家の犬」、「最後の問題」など、多くの短編および長編で構成されています。ドイルの緻密なプロットと魅力的なキャラクター描写は、シャーロック・ホームズを不朽の名作として位置づけ、彼の冒険は今なお世界中の読者に愛され続けています。',
                'cover_image' => 'cover_images/book33_ConanDoule.jpg',
                'book_manager_id' => $bookManagers[array_rand($bookManagers)],
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => '三銃士',
                'author' => 'アレクサンドル・デュマ',
                'publication_date' => '1844',
                'genre' => '歴史小説',
                'description' => '「三銃士」は、アレクサンドル・デュマによる歴史冒険小説であり、フランス文学の古典的名作です。物語は、若きダルタニャンが銃士隊に加入し、三銃士であるアトス、ポルトス、アラミスとともに冒険を繰り広げる姿を描いています。彼らは「一人は皆のために、皆は一人のために」というモットーのもと、フランス宮廷の陰謀や戦争、愛の試練に立ち向かいます。デュマの活き活きとしたキャラクター描写とテンポの良いストーリーテリングは、多くの読者に愛され続け、数多くの映画、舞台、テレビドラマに翻案されています。この作品は友情、勇気、名誉をテーマにしており、冒険小説としての魅力を持ちながら、歴史的な背景も豊かに描かれています。',
                'cover_image' => 'cover_images/book34_Mushketer.jpg',
                'book_manager_id' => $bookManagers[array_rand($bookManagers)],
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'ロミオとジュリエット',
                'author' => 'ウィリアム・シェイクスピア',
                'publication_date' => '1597',
                'genre' => 'ロマンス',
                'description' => '「ロミオとジュリエット」は、ウィリアム・シェイクスピアによる世界的に有名な悲劇です。物語は、対立するモンタギュー家とキャピュレット家の間に生まれた若い恋人たち、ロミオとジュリエットの悲劇的な愛を描いています。ヴェローナの町を舞台に、二人の愛は家族の対立と不幸な偶然により引き裂かれ、最終的には悲劇的な結末を迎えます。この作品は愛と憎しみ、運命の無情さ、若さの情熱と無謀さをテーマにし、詩的な台詞と深い感情表現が特徴です。「ロミオとジュリエット」は、シェイクスピアの代表作として広く知られ、多くの舞台、映画、音楽、文学に影響を与え続けています。',
                'cover_image' => 'cover_images/book35_Romeo.jpg',
                'book_manager_id' => $bookManagers[array_rand($bookManagers)],
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => '老人と海',
                'author' => 'アーネスト・ヘミングウェイ',
                'publication_date' => '1952',
                'genre' => '小説',
                'description' => '「老人と海」は、アーネスト・ヘミングウェイによる名作で、彼の代表作の一つです。物語はキューバの老漁師サンチャゴが、長い間魚を捕ることができなかった後、巨大なカジキマグロとの孤独な闘いに挑む姿を描いています。サンチャゴの決意と不屈の精神が試されるこの闘いを通じて、人間の尊厳と誇り、自然との闘いの美しさが強調されています。ヘミングウェイの簡潔で力強い文体は、物語の緊張感と深い哲学的テーマを際立たせています。この作品は1953年にピューリッツァー賞を受賞し、翌年にはノーベル文学賞を受賞するきっかけとなりました。今なお、多くの読者に感動を与え続ける文学の傑作です。',
                'cover_image' => 'cover_images/book36_TheSea.jpg',
                'book_manager_id' => $bookManagers[array_rand($bookManagers)],
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'ファウスト',
                'author' => 'ヨハン・ヴォルフガング・フォン・ゲーテ',
                'publication_date' => '1808',
                'genre' => '悲劇',
                'description' => '「ファウスト」は、ヨハン・ヴォルフガング・フォン・ゲーテによる傑作で、ドイツ文学の最高峰とされる作品です。物語は、知識欲に駆られた学者ファウスト博士が、悪魔メフィストフェレスと契約を結び、若さと無限の知識を求める姿を描いています。ファウストは契約により多くの冒険と誘惑を経験し、その過程で愛と絶望、救済と破滅を巡る深い哲学的テーマが探求されます。作品は、第一部と第二部から成り、特に第一部はマルガレーテ（グレートヒェン）との悲劇的な愛の物語として有名です。ゲーテの詩的で深遠な言語表現は、読者に強い感銘を与え、今なお多くの舞台や文学作品に影響を与え続けています。',
                'cover_image' => 'cover_images/book37_Faust.jpg',
                'book_manager_id' => $bookManagers[array_rand($bookManagers)],
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => '華氏451度',
                'author' => 'レイ・ブラッドベリ',
                'publication_date' => '1953',
                'genre' => 'サイエンスフィクション',
                'description' => '「華氏451度」は、レイ・ブラッドベリによる小説で、本が禁止され、破壊される未来の社会を描いたアンチユートピア作品です。主人公のガイ・モンタークは、本を焼却する消防士であり、内面の矛盾に直面し、自らや社会の意味について問い始めます。この小説は、思考の自由や文学の価値を失うことへの警告としても知られており、批判的思考や文化遺産の重要性について考えさせる作品です。',
                'cover_image' => 'cover_images/book38_451.jpg',
                'book_manager_id' => $bookManagers[array_rand($bookManagers)],
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => '誇りと偏見',
                'author' => 'ジェーン・オースティン',
                'publication_date' => '1813',
                'genre' => 'ロマンス小説',
                'description' => '「誇りと偏見」は、ジェーン・オースティンによる古典的なロマンス小説です。物語は、エリザベス・ベネットとフィッツウィリアム・ダーシーという2人の主要な登場人物を中心に展開されます。彼らはお互いに初めは誤解や偏見を抱きながらも、徐々にお互いの魅力を認め、愛し合うようになります。作品は、19世紀のイギリス社会を舞台に、貴族や上流階級の人々の生活や恋愛模様を描いています。オースティンの鋭い風刺とキャラクターの立体感が際立ち、愛と結婚、誇りと偏見という普遍的なテーマを探求しています。この小説は現代でも多くの読者に愛され、数々の映画や舞台化されています。',
                'cover_image' => 'cover_images/book39_Pride.jpg',
                'book_manager_id' => $bookManagers[array_rand($bookManagers)],
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'グレート・ギャツビー',
                'author' => 'F・スコット・フィッツジェラルド',
                'publication_date' => '1925',
                'genre' => '小説',
                'description' => '「偉大なるギャツビー」は、F・スコット・フィッツジェラルドによるアメリカ文学の名作です。物語は、1920年代のアメリカを舞台に、富と名声を得たジェイ・ギャツビーと、彼を取り巻く人々の姿を描いています。ギャツビーは、かつての恋人デイジーへの想いに取り憑かれ、彼女を取り戻すために様々な手段を講じますが、その過程で人間関係や社会の虚栄を浮き彫りにします。作品は、アメリカの夢と絶望、富と空虚さ、そして愛と喪失をテーマに、浮世離れした大人たちの姿を描いています。フィッツジェラルドのリッチな言葉遣いとキャラクターの複雑さが、多くの読者に感銘を与えています。',
                'cover_image' => 'cover_images/book40_Gatsby.jpg',
                'book_manager_id' => $bookManagers[array_rand($bookManagers)],
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => '審判',
                'author' => 'フランツ・カフカ',
                'publication_date' => '1925',
                'genre' => '長編小説',
                'description' => '「審判」は、フランツ・カフカによる未完の小説で、彼の代表作の一つです。物語は、銀行の職員ヨーゼフ・Kがある日突然、理由も告げられないまま逮捕され、見えない司法機関によって裁判にかけられる姿を描いています。彼は自らの無実を証明しようとするが、手続きは不透明で理不尽なものであり、次第に追い詰められていきます。カフカの独特な文体と不条理な状況描写は、現代社会の官僚主義や個人の無力感を象徴的に表現しています。この作品は、存在の不安と人間の孤立、理不尽な権力構造に対する鋭い洞察を提供し、多くの読者と批評家に強い印象を与え続けています。',
                'cover_image' => 'cover_images/book41_Process.jpg',
                'book_manager_id' => $bookManagers[array_rand($bookManagers)],
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'すばらしい新世界',
                'author' => 'オルダス・ハクスリー',
                'publication_date' => '1932',
                'genre' => 'ディストピア小説',
                'description' => '「すばらしい新世界」は、オルダス・ハクスリーによるディストピア小説で、未来社会の暗いビジョンを描いています。物語は、遺伝子操作と心理的条件付けにより管理された全体主義的な世界を舞台にしています。この社会では、幸福が安定の名のもとに強制され、人々は個性や自由を失っています。主人公のバーナード・マルクスとジョン・ザ・セイヴィッジは、この管理社会に疑問を抱き、対立する価値観を体現します。ハクスリーは、人間の本質や自由の意味、科学技術の進歩がもたらす倫理的問題について深く探求し、現代社会に対する鋭い風刺を提供しています。この作品は、哲学的なテーマと未来社会の警告として、多くの読者に影響を与え続けています。',
                'cover_image' => 'cover_images/book42_World.jpg',
                'book_manager_id' => $bookManagers[array_rand($bookManagers)],
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'ハムレット',
                'author' => 'ウィリアム・シェイクスピア',
                'publication_date' => '1603',
                'genre' => '悲劇',
                'description' => '「ハムレット」は、ウィリアム・シェイクスピアによる悲劇の一つで、世界文学の傑作とされています。物語は、デンマークの王子ハムレットが、亡き父王の亡霊から叔父クローディアスが父王を殺し、王位を奪ったことを聞かされ、復讐を決意するところから始まります。ハムレットは内面的な葛藤に苦しみながらも、策略を巡らし、最終的に復讐を果たそうとします。物語は復讐、裏切り、狂気、愛、死といった普遍的なテーマを探求しており、シェイクスピアの深い心理描写と詩的な言葉遣いが特徴です。特に「生きるべきか死ぬべきか」という有名な独白は、人生と存在の意義についての問いかけとして広く知られています。この作品は、数多くの舞台、映画、文学作品に影響を与え続けています。',
                'cover_image' => 'cover_images/book43_Hamlet.jpg',
                'book_manager_id' => $bookManagers[array_rand($bookManagers)],
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'トム・ソーヤーの冒険',
                'author' => 'マーク・トウェイン',
                'publication_date' => '1876',
                'genre' => '冒険小説',
                'description' => '「トム・ソーヤーの冒険」は、マーク・トウェインによる児童文学の古典で、19世紀アメリカのミシシッピ川沿いの小さな町を舞台に、トム・ソーヤーと彼の仲間たちの冒険を描いています。トムは友達のハックルベリー・フィン（ハック）やベッキー・サッチャーと共に、洞窟の探検、宝探し、川での冒険など、多くのスリリングな出来事を経験します。トムのいたずら好きで冒険心旺盛な性格が、彼の成長と友情を通して描かれています。',
                'cover_image' => 'cover_images/book44_Tom.jpg',
                'book_manager_id' => $bookManagers[array_rand($bookManagers)],
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'たんぽぽのお酒',
                'author' => 'レイ・ブラッドベリ',
                'publication_date' => '1957',
                'genre' => 'ファンタジー',
                'description' => '「たんぽぽのお酒」は、レイ・ブラッドベリによるノスタルジックな自伝的小説で、1928年の夏を舞台に、12歳のダグラス・スパルディングの成長と日々の出来事を描いています。ダグラスと彼の家族、友人たちとの生活を通じて、日常の喜びや悲しみ、驚きと発見の瞬間が詩的に描かれています。物語の中心には、ダグラスが夏の間に収穫したたんぽぽで作るお酒があり、それが彼の思い出と結びついています。ブラッドベリの感情豊かな描写と、魔法のような日常の瞬間が織りなすこの作品は、読者に子供時代の無垢な喜びと大人になる過程の複雑さを思い起こさせます。',
                'cover_image' => 'cover_images/book45_Wine.jpg',
                'book_manager_id' => $bookManagers[array_rand($bookManagers)],
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => '誰がために鐘は鳴る',
                'author' => 'アーネスト・ヘミングウェイ',
                'publication_date' => '1940',
                'genre' => '戦争小説',
                'description' => '「誰がために鐘は鳴る」は、アーネスト・ヘミングウェイによる戦争小説で、スペイン内戦を背景にしています。物語は、アメリカ人のロバート・ジョーダンという爆破工作員が、反ファシストのゲリラ部隊と共にスペインの橋を爆破する任務を引き受ける様子を描いています。彼はその過程で、仲間たちとの友情や恋人マリアとの愛、戦争の恐怖と自己犠牲について深く考えるようになります。タイトルはジョン・ダンの詩から引用され、人間の連帯感と死の避けられない現実を象徴しています。ヘミングウェイの簡潔で力強い文体と、戦争の残酷さと人間性の複雑さが見事に描かれているこの作品は、多くの読者に深い印象を与え続けています。',
                'cover_image' => 'cover_images/book46_Bell.jpg',
                'book_manager_id' => $bookManagers[array_rand($bookManagers)],
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'マーティン・イーデン',
                'author' => 'ジャック・ロンドン',
                'publication_date' => '1909',
                'genre' => '成長小説',
                'description' => '「マーティン・イーデン」は、ジャック・ロンドンによるアメリカ文学の名作で、主人公の成長と苦悩を描いた作品です。物語は、貧しいながらも野心的な青年マーティン・イーデンが、自らの才能を開花させながら社会で成功を目指す姿を追っています。彼は文学の道を選び、自らの価値観や信念を貫き通す中で、愛や人間関係、社会の仕組みに対する理解を深めていきます。一方で、成功と孤独、苦悩と矛盾、そして自己実現というテーマも重要な要素として取り入れられています。ロンドンの力強い筆致と哲学的な探求が組み合わさり、多くの読者に感銘を与える作品となっています。',
                'cover_image' => 'cover_images/book47_Edem.jpg',
                'book_manager_id' => $bookManagers[array_rand($bookManagers)],
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => '神曲',
                'author' => 'ダンテ・アリギエーリ',
                'publication_date' => '1320',
                'genre' => '詩',
                'description' => '「神曲」は、イタリアの詩人ダンテ・アリギエーリによる叙事詩で、キリスト教の信仰と哲学をテーマにした傑作です。物語は3部構成で、地獄（インフェルノ）、煉獄（プルガトリオ）、天国（パラディーゾ）に分かれており、主人公のダンテ自身が神秘的な旅を通じてこれらの領域を巡ります。物語は、人間の罪と贖い、神の摂理と人間の自由意志など、哲学的なテーマを探求しながら、キリスト教の教えや宇宙観を描き出しています。ダンテの詩的な表現と宗教的な洞察力が見事に融合したこの作品は、西洋文学の中でも最も重要な作品の一つとされています。',
                'cover_image' => 'cover_images/book48_Ad.jpg',
                'book_manager_id' => $bookManagers[array_rand($bookManagers)],
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'ファイト・クラブ',
                'author' => 'チャック・パラニューク',
                'publication_date' => '1996',
                'genre' => 'ブラック・ユーモア',
                'description' => '「ファイト・クラブ」は、チャック・パラニュークによる小説で、男性たちがルール無用の喧嘩を通じて男らしさや精神的な苦悩を表現する特異なクラブについて描かれています。主人公は名前のない男性で、彼と謎めいた友人タイラー・ダーデンが共同でこのクラブを創設し、それが地下組織から抜け出していく過程を描いています。この小説はアイデンティティ、消費社会、男らしさ、暴力、社会の制約からの自由への欲求などをテーマにしており、複雑なプロットと意外な展開が特徴です。興味深い物語と独特の文体が、現代文学の中で際立った作品の一つとされています。',
                'cover_image' => 'cover_images/book49_Fight.jpg',
                'book_manager_id' => $bookManagers[array_rand($bookManagers)],
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => '蝿の王',
                'author' => 'ウィリアム・ゴールディング',
                'publication_date' => '1954',
                'genre' => 'アラゴニズム',
                'description' => '「蝿の王」は、ウィリアム・ゴールディングによる寓話的な小説で、孤立した島での子供たちの集団の崩壊を描いています。航空機事故で孤立した一団の少年たちが、自給自足の生活を試みますが、組織や秩序が失われ、次第に暴力と混乱が支配するようになります。物語は、人間の本性や文明の脆さ、権力と支配、善と悪といったテーマを探求し、読者に考えさせる要素が豊富に含まれています。ゴールディングの鮮烈な文体と物語性は、多くの読者を引きつけ続けています。',
                'cover_image' => 'cover_images/book50_Lord.jpg',
                'book_manager_id' => $bookManagers[array_rand($bookManagers)],
                'created_at' => now(),
                'updated_at' => now(),
            ],


            // 必要に応じて本を増やす
        ]);
    }
}
